name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download
      working-directory: task_manger_clean_testing

    - name: Tidy-up modules
      run: go mod tidy
      working-directory: task_manger_clean_testing
      
    - name: Usecase Test
      run: go test ./usecases -v -coverprofile=coverage_usecases.out -covermode=atomic
      working-directory: task_manger_clean_testing

    - name: Controller Test
      run: go test ./delivery/controllers -v -coverprofile=coverage_controller.out -covermode=atomic
      working-directory: task_manger_clean_testing
